### ISSUE TITLE
Transfer `ipylgbst`

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets-contrib/jupyter-widgets-contrib.github.io#1]
# Target

- The code repository: https://github.com/jupyterlab-contrib/ipylgbst
- The npm package on npmjs.com (if available): `ipylgbst`
- The python package on pypi.org (if available): `ipylgbst`
- The conda-forge recipe on https://github.com/conda-forge (if available):
- The documentation website (if available):

# Reason

That package was initially moved to https://github.com/jupyterlab-contrib because the widgets contrib org did not exist at the time. 

# Checklist

- [x] You are owner of the repository you want to transfer
- Which role do you want to have in the `jupyter-widgets-contrib` organization (check one of):
  - [x] Help with all `jupyter-widgets-contrib` repositories
  - [ ] Help with the transferred repository only
  - [ ] I don't have time anymore to keep helping the project
- The transferred repository (check one of):
  - [x] Must keep the extension name
  - [ ] Cannot use the original name
  - [ ] I don't care
- [x] The code is available under a Open Source license
- [x] A license file is present in the code repository
- [x] The repository contains a README file describing:
  - [x] The provided feature(s)
  - [x] A picture illustrating the feature(s)
  - [x] The available options/settings (if applicable)
  - [x] How to install the extension
  - [x] _optional_ a Binder link to test the feature online
- [ ] _optional_ The frontend code (Typescript/Javascript) is tested
- [ ] _optional_ The backend code (Python) is tested
- [x] I certify the extension is not using exclusively paid-plan of any commercial service
- [x] I will help the transfer process on the code repository AND the built packages

> You must enable [two-factor authentication on GitHub](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by jtpio** [comment]
cc @DerThorsten @hbcarlos @DenisaCG for awareness

Moving the package here could make sense, unless there were other plans for having it in a different org.

**Comment by jtpio** [comment]
Looks like this package could instead be moved to the `jupyter-robotics` organization: https://github.com/jupyter-robotics

cc @ihuicatl to check if that would be ok, happy to help with the transfer.

**Comment by ihuicatl** [comment]
Sounds good to me. Thanks @jtpio! Anything I should do?

**Comment by ihuicatl** [comment]
@jtpio It looks like I still do not have the rights to do the transfer. It says:

> **Transfer ownership**
> Organization members cannot transfer repositories

**Comment by jtpio** [comment]
Are you an owner of the `jupyter-robotics` organization?

**Comment by ihuicatl** [comment]
yes, but maybe it's because I'm not part of `jupyterlab-contrib`?

**Comment by jtpio** [comment]
Maybe. I just invited you to join `jupyterlab-contrib` hopefully it will work now.

**Comment by ihuicatl** [comment]
That did it. All transferred now. What's the transfer process for the npm and pypi packages? Is it just changing the homepage?

**Comment by jtpio** [comment]
> What's the transfer process for the npm and pypi packages? Is it just changing the homepage?

For that package changing the links would be enough yes.

**Comment by jtpio** [comment]
Closing as `ipylgbst` has now been moved to the `jupyter-robotics` org: https://github.com/jupyter-robotics/ipylgbst

Thanks!
